---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stefanma/public_html
    - export REPOPATH=/home/stefanma/repositories/utor-mod20-chal01-react-portfolio
    - /bin/rm -R $DEPLOYPATH
    - /bin/cp -a $REPOPATH/. $DEPLOYPATH/
